### ISSUE TITLE
FOLDER ACCESS BLOCKED

### ISSUE THREAD

**Issue by Ganesha2282882** [mcgregol/JiantPondoOSv.1#1]
# FOLDER ACCESS BLOCKED
Windows Defender 

**Windows 10**

**Comment by mcgregol** [comment]
@Ganesha2282882 Could you be more specific?

**Comment by Ganesha2282882** [comment]
> @Ganesha2282882 Could you be more specific?

Windows Defender Freaks out and Protects my PC. This must be a virus.

**Comment by mcgregol** [comment]
@Ganesha2282882 Windows Defender has a history of blocking harmless batchfiles.  I assure you this isn't a virus and you can look over the code yourself, but if you still don't feel comfortable running it then don't.
